FROM php:7.4-fpm-alpine
RUN apk add --no-cache nginx
RUN docker-php-ext-install pdo_mysql
#COPY nginx.conf /etc/nginx/nginx.conf

#COPY index.php /var/www/html/

EXPOSE 80


CMD ["sh", "-c", "nginx && php-fpm"]
